import { useState } from "react";
import type { ResearchAssessment, PropertyResearchDecision } from "@shared/analysis";
import { brokerDraft } from "@/lib/research-view";
import { useI18n } from "@/i18n/i18n";
import { buttonClass, Field, inputClass, NumberField, Panel, useResearchText } from "./fields";

export function BrokerEditor({ address, assessment, decision, onChange }: { address: string; assessment: ResearchAssessment; decision: PropertyResearchDecision; onChange: (v: ResearchAssessment) => void }) {
  const tx = useResearchText(); const { language } = useI18n();
  const [kind, setKind] = useState<"first_contact" | "price" | "relisting" | "follow_up">("first_contact");
  const [includePrice, setIncludePrice] = useState(false);
  const [dialoguePrice, setDialoguePrice] = useState<number | null>(null);
  const [copied, setCopied] = useState(false);
  const generate = () => onChange({ ...assessment, brokerDraft: brokerDraft({ address, kind, includePrice, dialoguePrice, language, questions: [...assessment.questions.filter(q => !q.resolved).map(q => q.text).filter(Boolean), ...decision.criteria.filter(c => c.status === "unknown").map(c => c.reason)] }) });
  return <Panel title={tx("Mæglerdialog", "Agent discussion")}><p className="mb-4 text-sm text-ink-soft">{tx("Udkastet sendes ikke. Projektloft, reserve og maksimumpris deles ikke automatisk. Vælg særskilt, om et samtaleniveau må medtages.", "Drafts are not sent. Project ceiling, reserve and maximum price are never included automatically. Choose separately whether to include a discussion price.")}</p><div className="grid gap-4 sm:grid-cols-2"><Field label={tx("Anledning", "Purpose")}><select className={inputClass} value={kind} onChange={e => setKind(e.target.value as typeof kind)}><option value="first_contact">{tx("Første kontakt", "First contact")}</option><option value="price">{tx("Prisafklaring før fremvisning", "Price before viewing")}</option><option value="relisting">{tx("Spørgsmål om genudbud", "Relisting questions")}</option><option value="follow_up">{tx("Opfølgning", "Follow-up")}</option></select></Field><NumberField label={tx("Prisniveau til dialog (kr.)", "Discussion price (DKK)")} value={dialoguePrice} onChange={setDialoguePrice} /></div><label className="my-4 block text-sm"><input type="checkbox" checked={includePrice} onChange={e => setIncludePrice(e.target.checked)} /> {tx("Medtag aktivt det indtastede prisniveau i udkastet", "Explicitly include the entered discussion price in this draft")}</label><button className={buttonClass} onClick={generate}>{tx("Generér / erstat udkast", "Generate / replace draft")}</button><Field label={tx("Redigerbart udkast", "Editable draft")}><textarea className={`${inputClass} mt-3`} rows={13} value={assessment.brokerDraft} onChange={e => { setCopied(false); onChange({ ...assessment, brokerDraft: e.target.value }); }} /></Field><button className={`${buttonClass} mt-3`} disabled={!assessment.brokerDraft} onClick={async () => { try { await navigator.clipboard.writeText(assessment.brokerDraft); setCopied(true); } catch { setCopied(false); } }}>{copied ? tx("Kopieret", "Copied") : tx("Kopiér udkast", "Copy draft")}</button></Panel>;
}
