import { calculateProjectBudget, type BudgetItem, type ResearchAssessment, type BuyingProject } from "@shared/analysis";
import { researchPurchasePrice } from "@/lib/research-view";
import { buttonClass, Field, inputClass, Money, NumberField, Panel, TextField, useResearchText } from "./fields";

const categories: [BudgetItem["category"], string, string][] = [["transaction", "Handel og finansiering", "Transaction costs"], ["necessary_work", "Nødvendigt før indflytning", "Required before moving in"], ["improvement", "Ønskede forbedringer", "Improvements"], ["deferred_work", "Udskudte arbejder", "Deferred work"], ["advice", "Rådgivning / myndigheder", "Advice / permits"], ["relocation", "Flytning / dobbelt bolig", "Moving / temporary housing"], ["finance", "Projektfinansiering", "Project financing"], ["other", "Øvrige udgifter", "Other costs"], ["reserve", "Reserve", "Reserve"]];
export function BudgetEditor({ project, assessment, askingPrice, onChange }: { project: BuyingProject; assessment: ResearchAssessment; askingPrice: number; onChange: (v: ResearchAssessment) => void }) {
  const tx = useResearchText();
  const budget = calculateProjectBudget(project.totalBudget, assessment.budgetItems, researchPurchasePrice(assessment.selectedPurchasePrice, askingPrice));
  const updateItem = (id: string, partial: Partial<BudgetItem>) => onChange({ ...assessment, budgetItems: assessment.budgetItems.map(b => b.id === id ? { ...b, ...partial } : b) });
  const addItem = () => onChange({ ...assessment, budgetItems: [...assessment.budgetItems, { id: crypto.randomUUID(), label: tx("Ny post", "New item"), category: "necessary_work", low: null, high: null, vat: "included", vatRate: null, status: "assumption", source: "", observedAt: new Date().toISOString().slice(0, 10), necessary: true, include: true, coveredByItemId: null }] });
  return <Panel title={tx("Projektbudget", "Project budget")}>
    <p className="mb-4 text-sm text-ink-soft">{tx("Maksimal købspris = projektloft minus projektposter. Tomme nødvendige beløb er ukendte. Intervaller beskriver scenarier, ikke statistisk sikkerhed.", "Maximum purchase price = project ceiling minus project costs. Empty required amounts are unknown. Ranges describe scenarios, not statistical confidence.")}</p>
    <div className="grid gap-3 sm:grid-cols-2"><NumberField label={tx("Valgt købspris i scenario (tom = dagens udbud)", "Scenario purchase price (empty = asking price)")} value={assessment.selectedPurchasePrice} step={1000} onChange={n => onChange({ ...assessment, selectedPurchasePrice: n })} /><Field label={tx("Beslutningsscenario", "Decision scenario")}><select className={inputClass} value={assessment.budgetScenario} onChange={e => onChange({ ...assessment, budgetScenario: e.target.value as "base" | "stress" })}><option value="base">{tx("Basis", "Base")}</option><option value="stress">{tx("Belastning", "Stress")}</option></select></Field></div>
    <div className="my-4 grid gap-3 sm:grid-cols-2">{(["base", "stress"] as const).map(key => <div key={key} className="rounded-xl bg-surface-alt p-4"><h4 className="font-bold">{key === "base" ? tx("Basis", "Base") : tx("Belastning", "Stress")}</h4><dl className="mt-2 space-y-1 text-sm"><div>{tx("Maks. køb", "Maximum purchase")}: <strong><Money value={budget[key].maxPurchasePrice} /></strong></div><div>{tx("Samlet projekt", "Total project")}: <Money value={budget[key].projectTotal} /></div><div>{tx("Tilbage under loftet", "Headroom")}: <Money value={budget[key].headroom} /></div></dl></div>)}</div>
    {budget.unknownItems.length > 0 && <p role="status" className="mb-4 rounded-xl bg-warning-soft p-3 text-sm text-warning">{tx("Uafklarede beløb", "Unresolved costs")}: {budget.unknownItems.join(", ")}</p>}
    {budget.warnings.map(w => <p className="my-2 text-sm text-warning" key={w}>{w}</p>)}
    <div className="space-y-4">{assessment.budgetItems.map(item => <fieldset className="rounded-xl border border-border p-3" key={item.id}><legend className="px-1 text-sm font-bold">{item.label}</legend>
      <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3"><TextField label={tx("Post", "Item")} value={item.label} onChange={label => updateItem(item.id, { label })} /><Field label={tx("Kategori", "Category")}><select className={inputClass} value={item.category} onChange={e => updateItem(item.id, { category: e.target.value as BudgetItem["category"] })}>{categories.map(([v, da, en]) => <option value={v} key={v}>{tx(da, en)}</option>)}</select></Field><Field label={tx("Grundlag", "Basis")}><select className={inputClass} value={item.status} onChange={e => updateItem(item.id, { status: e.target.value as BudgetItem["status"] })}><option value="assumption">{tx("Brugerantagelse", "Assumption")}</option><option value="estimate">{tx("Overslag", "Estimate")}</option><option value="quote">{tx("Konkret tilbud", "Quote")}</option></select></Field>
      <NumberField label={tx("Lavt / basis (kr.)", "Low / base (DKK)")} value={item.low} step={1000} onChange={low => updateItem(item.id, { low })} /><NumberField label={tx("Højt / belastning (kr.)", "High / stress (DKK)")} value={item.high} step={1000} onChange={high => updateItem(item.id, { high })} /><Field label={tx("Moms", "VAT")}><select className={inputClass} value={item.vat} onChange={e => updateItem(item.id, { vat: e.target.value as BudgetItem["vat"] })}><option value="included">{tx("Inkluderet", "Included")}</option><option value="excluded">{tx("Ekskluderet", "Excluded")}</option><option value="not_applicable">{tx("Ikke relevant", "Not applicable")}</option><option value="unknown">{tx("Ukendt", "Unknown")}</option></select></Field>
      {item.vat === "excluded" && <NumberField label={tx("Momsrate (fx 0,25)", "VAT rate (e.g. 0.25)")} value={item.vatRate} step={0.01} onChange={vatRate => updateItem(item.id, { vatRate })} />}<TextField label={tx("Kilde / tilbudsreference", "Source / quote reference")} value={item.source} onChange={source => updateItem(item.id, { source })} /><Field label={tx("Dato", "Date")}><input type="date" className={inputClass} value={item.observedAt?.slice(0, 10) ?? ""} onChange={e => updateItem(item.id, { observedAt: e.target.value || null })} /></Field>
      {item.category === "reserve" && <Field label={tx("Allerede medregnet i tilbud", "Already included in quote")}><select className={inputClass} value={item.coveredByItemId ?? ""} onChange={e => updateItem(item.id, { coveredByItemId: e.target.value || null })}><option value="">{tx("Separat reserve", "Separate reserve")}</option>{assessment.budgetItems.filter(b => b.id !== item.id && b.category !== "reserve").map(b => <option key={b.id} value={b.id}>{b.label}</option>)}</select></Field>}</div>
      <div className="mt-3 flex flex-wrap items-center gap-4 text-sm"><label><input type="checkbox" checked={item.necessary} onChange={e => updateItem(item.id, { necessary: e.target.checked })} /> {tx("Nødvendig", "Required")}</label><label><input type="checkbox" checked={item.include} onChange={e => updateItem(item.id, { include: e.target.checked })} /> {tx("Med i scenario", "Include in scenario")}</label><button disabled={item.necessary} title={tx("Fjern markeringen Nødvendig før sletning", "Mark this item optional before removing it")} className="ml-auto text-danger underline disabled:opacity-40" onClick={() => onChange({ ...assessment, budgetItems: assessment.budgetItems.filter(b => b.id !== item.id) })}>{tx("Fjern post", "Remove item")}</button></div>
    </fieldset>)}</div><button className={`${buttonClass} mt-4`} onClick={addItem}>+ {tx("Tilføj budgetpost", "Add cost item")}</button>
  </Panel>;
}
