import { classifyConditionEvidence, type ResearchAssessment, type EvidenceStatus } from "@shared/analysis";
import type { Property } from "@shared/types/index";
import { safeDocumentUrl } from "@/lib/research-view";
import { buttonClass, Field, inputClass, NumberField, Panel, TextField, useResearchText } from "./fields";

export function EvidenceSelect({ value, onChange, label }: { value: EvidenceStatus; onChange: (v: EvidenceStatus) => void; label: string }) {
  const tx = useResearchText();
  return <Field label={label}><select className={inputClass} value={value} onChange={e => onChange(e.target.value as EvidenceStatus)}><option value="unknown">{tx("Ukendt", "Unknown")}</option><option value="reported">{tx("Oplyst, ikke kontrolleret", "Reported, unchecked")}</option><option value="verified">{tx("Manuelt dokumenteret", "Manually documented")}</option><option value="conflicting">{tx("Modstridende", "Conflicting")}</option></select></Field>;
}

export function EvidenceEditor({ property, assessment, onChange }: { property: Property; assessment: ResearchAssessment; onChange: (v: ResearchAssessment) => void }) {
  const tx = useResearchText();
  const update = (v: Partial<ResearchAssessment>) => onChange({ ...assessment, ...v });
  const condition = classifyConditionEvidence({ text: property.description, source: property.listingSource, listingEpisodeId: null, observedAt: property.updatedAt, validAt: null });
  const signalLabels: Record<string, string> = { needs_work: tx("Renoveringsbehov", "Work needed"), original_condition: tx("Oprindelig stand", "Original condition"), weak_potential: tx("Svagt salgssprog", "Weak sales language"), completed_work: tx("Udførte arbejder", "Completed work"), move_in_ready: tx("Indflytningsklar omtale", "Move-in ready wording"), demolition: tx("Nedrivning", "Demolition"), estate: tx("Dødsbo", "Estate"), unknown: tx("Ukendt", "Unknown") };
  return <div className="space-y-4"><Panel title={tx("Boligareal og soveværelser", "Residential area and bedrooms")}><p className="mb-4 text-sm text-ink-soft">{tx("Annonceareal og antal rum er bevarede udsagn. Kælder tæller ikke som bolig, og rum er ikke dokumentation for soveværelser. En manuel kontrol kræver en kilde.", "Listing area and room count remain reported facts. Basement is not residential area; rooms do not prove bedrooms. Manual verification requires a source.")}</p><div className="grid gap-3 sm:grid-cols-3">
    <NumberField label={tx("Dokumenteret boligareal (m²)", "Documented residential area (m²)")} value={assessment.residentialArea} onChange={residentialArea => update({ residentialArea })} /><EvidenceSelect label={tx("Arealgrundlag", "Area evidence")} value={assessment.areaEvidence} onChange={areaEvidence => update({ areaEvidence })} /><TextField label={tx("Arealkilde / side", "Area source / page")} value={assessment.areaSource} onChange={areaSource => update({ areaSource })} />
    <NumberField label={tx("Lovlige soveværelser", "Legal bedrooms")} value={assessment.legalBedrooms} onChange={legalBedrooms => update({ legalBedrooms })} /><EvidenceSelect label={tx("Soveværelsesgrundlag", "Bedroom evidence")} value={assessment.bedroomEvidence} onChange={bedroomEvidence => update({ bedroomEvidence })} /><TextField label={tx("Soveværelseskilde / side", "Bedroom source / page")} value={assessment.bedroomSource} onChange={bedroomSource => update({ bedroomSource })} /></div>
    <h4 className="mb-2 mt-5 font-bold">{tx("Øvrige ufravigelige krav", "Other hard requirements")}</h4><p className="mb-3 text-sm text-ink-soft">{tx("Tilføj fx støj, rådighed, lejemål eller antal boligenheder. Uafklarede krav forhindrer en positiv fremvisningsbeslutning.", "Add noise, availability, tenancy or number of units. Unresolved requirements prevent a positive viewing decision.")}</p>
    {assessment.hardRequirements.map(r => <div key={r.id} className="mb-3 grid items-end gap-2 sm:grid-cols-3"><TextField label={tx("Krav", "Requirement")} value={r.label} onChange={label => update({ hardRequirements: assessment.hardRequirements.map(v => v.id === r.id ? { ...v, label } : v) })} /><Field label={tx("Status", "Status")}><select className={inputClass} value={r.status} onChange={e => update({ hardRequirements: assessment.hardRequirements.map(v => v.id === r.id ? { ...v, status: e.target.value as typeof r.status } : v) })}><option value="unknown">{tx("Ukendt", "Unknown")}</option><option value="met">{tx("Opfyldt", "Met")}</option><option value="failed">{tx("Ikke opfyldt", "Not met")}</option></select></Field><TextField label={tx("Begrundelse og kilde", "Reason and source")} value={r.reason} onChange={reason => update({ hardRequirements: assessment.hardRequirements.map(v => v.id === r.id ? { ...v, reason } : v) })} /></div>)}<button className={buttonClass} onClick={() => update({ hardRequirements: [...assessment.hardRequirements, { id: crypto.randomUUID(), label: "", status: "unknown", reason: "", hard: true }] })}>+ {tx("Tilføj krav", "Add requirement")}</button>
  </Panel><Panel title={tx("Stand: tekstspor", "Condition: text evidence")}><p className="mb-3 text-sm text-ink-soft">{tx("Maskinelt fortolket tekst fra den aktuelle annonce. Ingen teknisk diagnose og ingen automatisk historisk standstilknytning.", "Machine-interpreted current listing text. No technical diagnosis or automatic historical condition association.")}</p><div className="flex flex-wrap gap-2">{condition.signals.map(s => <span key={s} className="rounded-full bg-surface-alt px-3 py-1 text-sm">{signalLabels[s]}</span>)}</div>{condition.excerpts.map((e, i) => <blockquote key={i} className="mt-3 border-l-2 border-border-strong pl-3 text-sm">“{e.text}”</blockquote>)}<p className="mt-3 text-xs text-ink-soft">{condition.source} · {condition.observedAt.slice(0, 10)} · {condition.method} {condition.methodVersion}</p></Panel>
  <Panel title={tx("Dokumenter og kilder", "Documents and sources")}><p className="mb-3 text-sm text-ink-soft">{tx("Tilføj et dokumentlink og en side-/afsnitshenvisning. Gem modstridende kilder hver for sig.", "Add a document link and page/section reference. Keep conflicting sources separately.")}</p>{assessment.documents.map(doc => {
    const edit = (v: Partial<typeof doc>) => update({ documents: assessment.documents.map(d => d.id === doc.id ? { ...d, ...v } : d) });
    return <div className="mb-4 rounded-xl border border-border p-3" key={doc.id}><div className="grid gap-3 sm:grid-cols-2"><TextField label={tx("Titel", "Title")} value={doc.title} onChange={title => edit({ title })} /><TextField label={tx("Link (https://)", "Link (https://)")} value={doc.url} onChange={url => edit({ url })} /><TextField label={tx("Side / afsnit", "Page / section")} value={doc.reference} onChange={reference => edit({ reference })} /><TextField label={tx("Klassifikation", "Classification")} value={doc.classification} onChange={classification => edit({ classification })} /><TextField label={tx("Kilde", "Source")} value={doc.source} onChange={source => edit({ source })} /><EvidenceSelect label={tx("Kontrolstatus", "Verification status")} value={doc.status} onChange={status => edit({ status })} /><Field label={tx("Observationsdato", "Observed date")}><input type="date" className={inputClass} value={doc.observedAt?.slice(0, 10) ?? ""} onChange={e => edit({ observedAt: e.target.value || null })} /></Field></div><div className="mt-3 flex justify-between">{safeDocumentUrl(doc.url) && <a className="text-sm underline" target="_blank" rel="noopener noreferrer" href={safeDocumentUrl(doc.url)}>{tx("Åbn dokument", "Open document")} ↗</a>}<button className="text-sm text-danger underline" onClick={() => update({ documents: assessment.documents.filter(d => d.id !== doc.id) })}>{tx("Fjern", "Remove")}</button></div></div>;
  })}<button className={buttonClass} onClick={() => update({ documents: [...assessment.documents, { id: crypto.randomUUID(), title: "", url: "", reference: "", classification: "", source: "", observedAt: new Date().toISOString().slice(0, 10), status: "unknown" }] })}>+ {tx("Tilføj dokument", "Add document")}</button></Panel>
  <Panel title={tx("Åbne spørgsmål og egne noter", "Open questions and notes")}>{assessment.questions.map(q => <div className="mb-2 flex items-center gap-2" key={q.id}><input aria-label={tx("Afklaret", "Resolved")} type="checkbox" checked={q.resolved} onChange={e => update({ questions: assessment.questions.map(v => v.id === q.id ? { ...v, resolved: e.target.checked } : v) })} /><input aria-label={tx("Spørgsmål", "Question")} className={inputClass} value={q.text} onChange={e => update({ questions: assessment.questions.map(v => v.id === q.id ? { ...v, text: e.target.value } : v) })} /></div>)}<button className={`${buttonClass} mb-3`} onClick={() => update({ questions: [...assessment.questions, { id: crypto.randomUUID(), text: "", resolved: false }] })}>+ {tx("Tilføj spørgsmål", "Add question")}</button><TextField label={tx("Private noter", "Private notes")} value={assessment.notes} multiline onChange={notes => update({ notes })} /></Panel></div>;
}
