import { useState } from "react";
import { calculatePriceMetrics, scenarioAskingCeiling, type ResearchAssessment, type ProjectBudgetResult } from "@shared/analysis";
import type { Property } from "@shared/types/index";
import type { ResearchHistoryResponse } from "@shared/types/research-api";
import { safeDocumentUrl } from "@/lib/research-view";
import { researchListingTime } from "@/lib/research-listing-time";
import { Money, NumberField, Panel, Percent, useResearchText } from "./fields";

export function HistoryPanel({ property, history, assessment, budget }: { property: Property; history?: ResearchHistoryResponse; assessment: ResearchAssessment; budget: ProjectBudgetResult }) {
  const tx = useResearchText();
  const [scenarioFall, setScenarioFall] = useState<number | null>(null);
  const { time, firstAsking, events } = researchListingTime(property, history);
  const metrics = calculatePriceMetrics({ firstAsking, currentAsking: property.price, lastAsking: null, soldPrice: null, targetPrice: budget[assessment.budgetScenario].maxPurchasePrice });
  return <div className="space-y-4"><Panel title={tx("Prisdialog: fire adskilte beløb", "Price discussion: four separate figures")}><dl className="grid gap-3 sm:grid-cols-2"><div className="rounded-xl bg-surface-alt p-3"><dt className="text-xs text-ink-soft">{tx("Dagens udbud", "Current asking price")} · {property.updatedAt.slice(0, 10)}</dt><dd className="mt-1 text-lg font-bold"><Money value={property.price} /></dd></div><div className="rounded-xl bg-surface-alt p-3"><dt className="text-xs text-ink-soft">{tx("Dokumenteret første pris i aktuelt forløb", "Documented first price in current campaign")}</dt><dd className="mt-1 text-lg font-bold"><Money value={firstAsking} /></dd></div><div className="rounded-xl bg-surface-alt p-3"><dt className="text-xs text-ink-soft">{tx("Privat maksimal købspris", "Private maximum purchase price")}</dt><dd className="mt-1 text-lg font-bold"><Money value={budget[assessment.budgetScenario].maxPurchasePrice} /></dd></div><div className="rounded-xl bg-surface-alt p-3"><dt className="text-xs text-ink-soft">{tx("Valgt pris i budgetscenario", "Chosen budget scenario price")}</dt><dd className="mt-1 text-lg font-bold"><Money value={assessment.selectedPurchasePrice ?? property.price} /></dd></div></dl><div className="mt-4 space-y-1 text-sm"><p>{tx("Allerede nedsat", "Already reduced")}: <Percent value={metrics.alreadyReducedPercent} /></p><p>{tx("Nødvendigt yderligere afslag til dit budget", "Further reduction required for your budget")}: {metrics.noDiscountRequired ? tx("Intet afslag kræves", "No reduction required") : <><Money value={metrics.additionalDiscountAmount} /> · <Percent value={metrics.additionalDiscountPercent} /></>}</p><p>{tx("Nødvendigt samlet fald fra første udbud", "Required total fall from first asking")}: <Percent value={metrics.totalRequiredFallPercent} /></p></div><p className="mt-3 text-xs text-ink-soft">{tx("Prisreferencen ovenfor viser handler med tilsvarende liggetid. Et samlet historisk fald anvendes aldrig som ekstra rabat på dagens udbud.", "The price reference above shows sales with similar marketing duration. Historical total falls are never applied as an extra discount on today's asking price.")}</p></Panel>
    <Panel title={tx("Udbudsloft i valgt scenario", "Asking ceiling in chosen scenario")}><NumberField label={tx("Valgt samlet prisfald (%)", "Chosen total fall (%)")} value={scenarioFall} step={0.1} onChange={setScenarioFall} /><p className="mt-3 font-semibold"><Money value={scenarioAskingCeiling(budget[assessment.budgetScenario].maxPurchasePrice, scenarioFall)} /></p><p className="mt-2 text-xs text-ink-soft">{tx("Et personligt søgescenario, ikke en rimelig markedspris. Samlet fald regnes fra første udbud; det er ikke en ekstra rabat på dagens pris.", "A personal search scenario, not a fair market price. Total fall starts at first asking; it is not an additional discount on today's price.")}</p></Panel>
    <Panel title={tx("Prisforløb og tidsdefinitioner", "Price history and time definitions")}><div className="grid gap-3 text-sm sm:grid-cols-3"><div>{tx("Seneste udbudsperiode", "Latest listing episode")}<p className="font-bold">{time.latestEpisodeDays ?? tx("Ukendt", "Unknown")}</p></div><div>{tx("Dokumenteret aktiv tid", "Documented active time")}<p className="font-bold">{time.activeDays ?? tx("Ukendt", "Unknown")}</p></div><div>{tx("Kalendertid fra første udbud", "Calendar days from first listing")}<p className="font-bold">{time.calendarDays ?? tx("Ukendt", "Unknown")}</p></div></div><p className="my-3 text-xs text-ink-soft">{tx("Observationsdato er ikke første udbudsdag. Pauser tæller ikke som aktiv tid. Fjernet betyder ikke solgt.", "Observation date is not first listing date. Pauses are excluded from active time. Removed does not mean sold.")}</p>{events.length === 0 && <p className="text-sm text-ink-soft">{tx("Ingen dokumenterede prisbegivenheder endnu.", "No documented price events yet.")}</p>}<ol className="space-y-3">{events.map(e => <li key={e.id} className="border-l-2 border-border-strong pl-3 text-sm"><p className="font-semibold">{e.eventDate ? e.datePrecision === "month" ? e.eventDate.slice(0, 7) : e.eventDate : tx("Hændelsesdato ukendt", "Event date unknown")} · {e.eventType} {e.price !== null && <>· <Money value={e.price} /></>}</p><p className="text-xs text-ink-soft">{e.source} · {tx("Observeret", "Observed")} {e.observedAt.slice(0, 10)} · {e.datePrecision} {safeDocumentUrl(e.sourceUrl ?? "") && <a className="underline" href={safeDocumentUrl(e.sourceUrl!)} target="_blank" rel="noopener noreferrer">{tx("Kilde", "Source")} ↗</a>}</p></li>)}</ol></Panel>
    <Panel title={tx("Kildespor og konflikter", "Source trail and conflicts")}><p className="mb-3 text-xs text-ink-soft">{tx("Ukendt, utilgængelig og undersøgt uden fund er adskilte statusser. Modstridende observationer bevares.", "Unknown, unavailable and investigated with no result are distinct states. Conflicting observations are retained.")}</p><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr><th className="p-2">{tx("Felt / værdi", "Field / value")}</th><th className="p-2">{tx("Kilde / metode", "Source / method")}</th><th className="p-2">{tx("Gyldig / observeret", "Effective / observed")}</th><th className="p-2">{tx("Status", "Status")}</th></tr></thead><tbody>{(history?.observations ?? []).map(o => <tr key={o.id} className="border-t border-border"><td className="max-w-64 break-words p-2">{o.fieldName}<br />{JSON.stringify(o.value)}</td><td className="p-2">{o.source}<br />{o.method}{o.sourceFile && <p className="text-xs">{o.sourceFile} · {o.sourceSheet} · {o.sourceRow} · {o.sourceVersion}</p>}</td><td className="p-2">{o.datePrecision === "month" ? o.effectiveDate?.slice(0, 7) : o.effectiveDate ?? "?"}<br />{o.observedAt.slice(0, 10)}</td><td className="p-2">{o.verificationStatus}<br />{o.dataMode}</td></tr>)}</tbody></table></div></Panel></div>;
}
