import { useMemo, useState } from "react";
import { Link } from "react-router-dom";
import { calculatePriceMetrics, researchDays, summarizeResearchTransactions, type ResearchAnalysisFilters, type ResearchTransaction, type ComparableSelection } from "@shared/analysis";
import type { PropertyType } from "@shared/types/index";
import { downloadSnapshot } from "@/lib/research-view";
import { buttonClass, Field, inputClass, Money, NumberField, Panel, Percent, TextField, useResearchText } from "./fields";
import { SalesMap } from "./sales-map";

export function ResearchStatistics({ transactions, dataVersion, propertyType, selections = [], onSelections, minResidentialArea }: {
  transactions: ResearchTransaction[]; dataVersion: string; propertyType?: PropertyType; selections?: ComparableSelection[];
  onSelections?: (v: ComparableSelection[]) => void; minResidentialArea?: number;
}) {
  const tx = useResearchText();
  const [filters, setFilters] = useState<ResearchAnalysisFilters>({ timeDefinition: "latest_episode_days", propertyTypes: propertyType ? [propertyType] : [], dataVersion, calculatedAt: new Date().toISOString() });
  const [focused, setFocused] = useState<string | null>(null);
  const [showMap, setShowMap] = useState(false);
  const runFilters = { ...filters, dataVersion };
  const system = useMemo(() => summarizeResearchTransactions(transactions, runFilters), [transactions, dataVersion, filters]);
  const result = useMemo(() => summarizeResearchTransactions(transactions, { ...runFilters, excludedTransactionIds: selections.filter(s => !s.included).map(s => s.transactionId) }), [transactions, dataVersion, filters, selections]);
  const update = (value: Partial<ResearchAnalysisFilters>) => { setFilters(f => ({ ...f, ...value, calculatedAt: new Date().toISOString() })); setFocused(null); };
  const choose = (id: string, partial: Partial<ComparableSelection>) => {
    const old = selections.find(s => s.transactionId === id) ?? { transactionId: id, included: true, reason: "" };
    onSelections?.([...selections.filter(s => s.transactionId !== id), { ...old, ...partial }]);
  };
  const rows = focused ? system.transactions.filter(t => t.id === focused) : system.transactions;
  const points = result.transactions.flatMap(row => {
    const days = researchDays(row, filters.timeDefinition);
    const fall = calculatePriceMetrics({ firstAsking: row.firstAsking, currentAsking: null, lastAsking: row.lastAsking, soldPrice: row.soldPrice, targetPrice: null }).historicalTotalFallPercent;
    return days === null || fall === null ? [] : [{ row, days, fall }];
  });
  const maxDays = Math.max(1, ...points.map(p => p.days));
  const minFall = Math.min(0, ...points.map(p => p.fall));
  const maxFall = Math.max(1, ...points.map(p => p.fall));
  return <Panel title={tx("Handler bag prisreferencen", "Transactions behind the reference")}>
    <p className="mb-4 text-sm text-ink-soft">{tx("Kun dokumenterede afsluttede handler fra reelle kilder. Aktive og fjernede annoncer holdes ude. Ingen sandsynlighed for sælgers accept og ingen ekstra stand-/sæsonrabat.", "Only documented completed transactions from real sources. Active and removed listings are excluded. This is not a probability of seller acceptance or an additional condition/season discount.")}</p>
    <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3"><TextField label={tx("Kommune", "Municipality")} value={filters.municipality ?? ""} onChange={municipality => update({ municipality: municipality || undefined })} /><TextField label={tx("Postnummer", "Postal code")} value={filters.postalCode ?? ""} onChange={postalCode => update({ postalCode: postalCode || undefined })} />
    <Field label={tx("Boligtype", "Property type")}><select className={inputClass} value={filters.propertyTypes?.[0] ?? ""} onChange={e => update({ propertyTypes: e.target.value ? [e.target.value as PropertyType] : [] })}><option value="">{tx("Alle", "All")}</option>{[...new Set([...(propertyType ? [propertyType] : []), ...transactions.map(t => t.propertyType)])].map(t => <option key={t}>{t}</option>)}</select></Field>
    <NumberField label={tx("Mindste bolig-m²", "Minimum residential m²")} value={filters.minArea ?? null} onChange={v => update({ minArea: v ?? undefined })} /><NumberField label={tx("Største bolig-m²", "Maximum residential m²")} value={filters.maxArea ?? null} onChange={v => update({ maxArea: v ?? undefined })} /><Field label={tx("Liggetidsdefinition", "Time definition")}><select className={inputClass} value={filters.timeDefinition} onChange={e => update({ timeDefinition: e.target.value as ResearchAnalysisFilters["timeDefinition"] })}><option value="latest_episode_days">{tx("Seneste udbudsperiode", "Latest listing episode")}</option><option value="active_days">{tx("Dokumenteret aktiv tid", "Documented active days")}</option><option value="calendar_days">{tx("Kalendertid fra første udbud", "Calendar days from first listing")}</option></select></Field>
    <Field label={tx("Solgt fra", "Sold from")}><input className={inputClass} type="date" value={filters.saleFrom ?? ""} onChange={e => update({ saleFrom: e.target.value || undefined })} /></Field><Field label={tx("Solgt til", "Sold to")}><input className={inputClass} type="date" value={filters.saleTo ?? ""} onChange={e => update({ saleTo: e.target.value || undefined })} /></Field><NumberField label={tx("Salgsmåned (1–12)", "Sale month (1–12)")} value={filters.saleMonth ?? null} onChange={v => update({ saleMonth: v ?? undefined })} /></div>
        <details className="my-4"><summary className="cursor-pointer text-sm font-semibold">{tx("Flere filtre", "More filters")}</summary><div className="mt-3 grid gap-3 sm:grid-cols-3"><TextField label={tx("Gade", "Street")} value={filters.street ?? ""} onChange={street => update({ street: street || undefined })} /><NumberField label={tx("Mindste første udbud", "Minimum first asking")} value={filters.minFirstAsking ?? null} onChange={v => update({ minFirstAsking: v ?? undefined })} /><NumberField label={tx("Største første udbud", "Maximum first asking")} value={filters.maxFirstAsking ?? null} onChange={v => update({ maxFirstAsking: v ?? undefined })} /><NumberField label={tx("Mindste salgspris", "Minimum sale price")} value={filters.minSoldPrice ?? null} onChange={v => update({ minSoldPrice: v ?? undefined })} /><NumberField label={tx("Største salgspris", "Maximum sale price")} value={filters.maxSoldPrice ?? null} onChange={v => update({ maxSoldPrice: v ?? undefined })} /><label className="self-end text-sm"><input type="checkbox" checked={!!filters.estateOnly} onChange={e => update({ estateOnly: e.target.checked })} /> {tx("Kun dokumenteret dødsbo (ikke stand)", "Documented estate only (not condition)")}</label><label className="text-sm"><input type="checkbox" checked={!!filters.requireVerifiedArea} onChange={e => update({ requireVerifiedArea: e.target.checked })} /> {tx("Kun kontrolleret areal", "Verified area only")}</label></div></details>
    <button className={`${buttonClass} my-2`} onClick={() => setShowMap(!showMap)}>{showMap ? tx("Skjul kort", "Hide map") : tx("Vis kort og områdefilter", "Show map and area filter")}</button>
    {showMap && <SalesMap rows={focused ? result.transactions.filter(t => t.id === focused) : result.transactions} onFilter={update} onFocus={setFocused} />}
    <div className="my-4 flex flex-wrap gap-3 text-sm"><label><input type="checkbox" checked={!!filters.strictRenovation} onChange={e => update({ strictRenovation: e.target.checked })} /> {tx("Stramt renoveringsudvalg", "Strict renovation selection")}</label>{minResidentialArea && <button className="underline" onClick={() => update({ minArea: minResidentialArea })}>{tx("Brug projektets arealkrav", "Use project minimum area")}</button>}<button className="ml-auto underline" onClick={() => { update({ minDays: undefined, maxDays: undefined }); setFocused(null); }}>{tx("Vis alle tidsgrupper", "Show all time groups")}</button></div>
    <div className="grid gap-2 sm:grid-cols-3"><div className="rounded-xl bg-surface-alt p-3 text-sm">{tx("Systemudvalg", "System selection")}: <strong>{system.selectedCount}</strong><br />{tx("Brugerjusteret", "User adjusted")}: <strong>{result.selectedCount}</strong> · {result.propertyCount} {tx("ejendomme", "properties")}</div><div className="rounded-xl bg-surface-alt p-3 text-sm">{tx("Median samlet fald", "Median total fall")}: <strong><Percent value={result.totalFall.median} /></strong><br />Q1 / Q3: <Percent value={result.totalFall.q1} /> / <Percent value={result.totalFall.q3} /><br />{tx("Gennemsnit", "Mean")}: <Percent value={result.totalFall.mean} /></div><div className="rounded-xl bg-surface-alt p-3 text-sm">{tx("Median fra sidste pris", "Median from last asking")}: <strong><Percent value={result.lastDiscount.median} /></strong><br />{tx("Salgspris / bolig-m²", "Sale price / residential m²")}: <Money value={result.pricePerResidentialSqm.median} /></div></div>
    <p className="my-3 text-xs text-ink-soft">{tx("Dækning (samlet fald / sidste afslag / m²)", "Coverage (total fall / last discount / m²)")}: {result.totalFall.count}/{result.selectedCount} · {result.lastDiscount.count}/{result.selectedCount} · {result.pricePerResidentialSqm.count}/{result.selectedCount}. {tx("Q1/median/Q3 er historiske fordelingspunkter, ikke et konfidensinterval.", "Q1/median/Q3 are historical distribution points, not a confidence interval.")}</p>
    {result.warnings.map(w => <p key={w} role="status" className="my-2 rounded-xl bg-warning-soft p-3 text-sm text-warning-text">{w}</p>)}
    <div className="my-4 grid grid-cols-2 gap-2 sm:grid-cols-5">{system.groups.map(g => <button key={g.label} className={`${buttonClass} rounded-xl text-left ${filters.minDays === g.min ? "ring-2 ring-brand" : ""}`} onClick={() => update({ minDays: g.min, maxDays: g.max ?? undefined })}><strong>{g.label} {tx("dage", "days")}</strong><br />{g.totalFall.count} {tx("prispar", "price pairs")}<br /><Percent value={g.totalFall.median} /></button>)}</div>
    {points.length > 0 && <div className="my-4"><p className="text-sm font-bold">{tx("Liggetid mod samlet prisfald — vælg et punkt", "Days on market versus total fall — select a point")}</p><svg viewBox="0 0 680 235" className="w-full rounded-xl bg-surface-alt" role="img" aria-label={tx("Liggetid mod prisfald", "Days on market versus price fall")}><line x1="45" y1="195" x2="650" y2="195" stroke="currentColor" opacity=".3" /><line x1="45" y1="20" x2="45" y2="195" stroke="currentColor" opacity=".3" /><text x="6" y="25" fontSize="11" fill="currentColor">{maxFall.toFixed(1)}%</text><text x="6" y="195" fontSize="11" fill="currentColor">{minFall.toFixed(1)}%</text><text x="45" y="217" fontSize="11" fill="currentColor">0</text><text x="600" y="217" fontSize="11" fill="currentColor">{maxDays} d</text>{points.map(({ row, days, fall }) => <circle key={row.id} cx={45 + days / maxDays * 600} cy={195 - (fall - minFall) / (maxFall - minFall) * 165} r={focused === row.id ? 8 : 5} fill="var(--color-brand)" opacity=".75" tabIndex={0} role="button" aria-label={`${row.address}, ${days}, ${fall.toFixed(2)}%`} onClick={() => setFocused(row.id)} onKeyDown={e => { if (e.key === "Enter" || e.key === " ") setFocused(row.id); }}><title>{row.address} · {days} · {fall.toFixed(2)}%</title></circle>)}</svg>{focused && <button className="mt-2 text-sm underline" onClick={() => setFocused(null)}>{tx("Fjern punktvalg", "Clear point selection")}</button>}</div>}
    {system.selectedCount === 0 && <p className="my-5 text-sm text-ink-soft">{tx("Ingen brugbare handler i dette udvalg. Importér dokumenterede handler eller ændr filtrene; manglende data giver ingen automatisk prisreference.", "No usable transactions in this selection. Import documented sales or change the filters; missing data produces no automatic price reference.")}</p>}
    <div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b border-border"><th className="p-2">{tx("Handel / kilde", "Sale / source")}</th><th className="p-2">{tx("Arealgrundlag", "Area basis")}</th><th className="p-2">{tx("Første / sidste / salg", "First / last / sale")}</th><th className="p-2">{tx("Samlet / sidste fald", "Total / last fall")}</th><th className="p-2">{tx("Dage", "Days")}</th>{onSelections && <th className="p-2">{tx("Dit arbejdsudvalg", "Your selection")}</th>}</tr></thead><tbody>{rows.map(row => {
      const metrics = calculatePriceMetrics({ firstAsking: row.firstAsking, currentAsking: null, lastAsking: row.lastAsking, soldPrice: row.soldPrice, targetPrice: null });
      const selected = selections.find(s => s.transactionId === row.id);
      return <tr key={row.id} className="border-b border-border align-top"><td className="p-2"><Link className="font-semibold underline" to={`/property/${row.propertyId}`}>{row.address}</Link><div>{row.saleDate}</div><details className="mt-1 text-xs"><summary className="cursor-pointer">{row.source}</summary><p>{row.transactionIdentity}</p><p>{row.observedAt}</p><p>{row.condition?.text ?? tx("Ingen historisk standstekst", "No historical condition text")}</p><p>{tx("Foreslået ud fra de viste filtre; stand og enhed skal kontrolleres.", "Suggested by displayed filters; check condition and unit type.")}</p></details></td><td className="p-2">{row.residentialArea ?? "?"} m²<br /><span className="text-xs">{row.areaDefinition} · {row.areaEvidence}<br />{row.areaAtSale ? tx("Ved salg", "At sale") : tx("Senere / ukendt dato", "Later / unknown date")}</span></td><td className="p-2"><Money value={row.firstAsking} /><br /><Money value={row.lastAsking} /><br /><Money value={row.soldPrice} /></td><td className="p-2"><Percent value={metrics.historicalTotalFallPercent} /><br /><Percent value={metrics.historicalLastDiscountPercent} /></td><td className="p-2">{researchDays(row, filters.timeDefinition) ?? "?"}</td>{onSelections && <td className="min-w-40 p-2"><label><input type="checkbox" checked={selected?.included ?? true} onChange={e => choose(row.id, { included: e.target.checked })} /> {tx("Medtag", "Include")}</label><input aria-invalid={selected?.included === false && !selected.reason.trim()} aria-label={tx("Begrundelse for udvalg", "Selection reason")} placeholder={tx("Begrundelse", "Reason")} className={inputClass} value={selected?.reason ?? ""} onChange={e => choose(row.id, { reason: e.target.value })} /><button className="mt-2 text-xs underline" onClick={() => choose(row.id, { included: true })}>{selected?.included === true ? tx("Valgt til fremvisningspakke", "Selected for viewing pack") : tx("Vælg til fremvisningspakke", "Select for viewing pack")}</button></td>}</tr>;
    })}</tbody></table></div>
    <details className="my-4 text-sm"><summary className="cursor-pointer font-semibold">{tx("Datadækning og udelukkelsesgrunde", "Coverage and exclusions")}</summary><p className="my-2">{tx("Mangler første / sidste pris / areal / tekst / tid", "Missing first / last price / area / text / time")}: {result.missing.firstAsking} / {result.missing.lastAsking} / {result.missing.area} / {result.missing.text} / {result.missing.validDays}</p><ul className="space-y-1">{result.excluded.map((e, i) => <li key={`${e.transactionId}-${i}`}>{transactions.find(t => t.id === e.transactionId)?.address ?? e.transactionId}: {e.reason}</li>)}</ul></details>
    <div className="flex flex-wrap items-center justify-between gap-2 text-xs text-ink-soft"><span>{result.snapshot.methodVersion} · {dataVersion} · {result.snapshot.calculatedAt.slice(0, 10)}</span><button className={buttonClass} onClick={() => downloadSnapshot({ ...result, transactionData: result.transactions }, "boligdata-analyse.json")}>{tx("Eksportér analysesnapshot", "Export analysis snapshot")}</button></div>
  </Panel>;
}
